import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'

interface Animal {
  id: string
  name: string
  scientific: string
  archetype: string
  feature: string
  habitat: string
}

interface Catalog {
  run: string
  accessDate: string
  animals: Animal[]
}

const root = resolve(dirname(new URL(import.meta.url).pathname), '../../..')
const catalogPath = join(root, 'tools/animal-onboarding/expansion-100.json')
const catalog = JSON.parse(await readFile(catalogPath, 'utf8')) as Catalog
const sourcePath = `assets/candidates/${catalog.run}/intake.json`
const rankingPath = `assets/candidates/${catalog.run}/candidate-ranking.json`

const intake = {
  $comment: 'Expansion from 25 to 100 animals. Every candidate is independently project-authored from deterministic Blender primitives. The retained generator, per-animal catalogue entry, generated source GLB and hashes form the complete source/rights chain. Human science, anatomy, materials, motion, narration and production approval remain pending.',
  recordedOn: catalog.accessDate,
  candidates: catalog.animals.map((animal) => ({
    id: animal.id,
    name: animal.name,
    scientificName: animal.scientific,
    source: 'project-authored',
    sourcePage: 'project-authored (no upstream)',
    downloadURL: `assets/candidates/${catalog.run}/${animal.id}/archive/build_expansion_animal.py`,
    format: 'GLB-native source generated by deterministic Blender Python',
    author: 'Prehistoric Animal Museum (project-authored)',
    license: 'CC0-1.0',
    licenseEvidence: 'Project-authored deterministic primitive model; archived generator and exact per-animal input entry reproduce the source GLB.',
    animated: 'yes (project-authored 8-second Idle in normalization)',
    redistribution: 'allowed without restriction under CC0-1.0',
    downloadAccess: 'local reproducible source',
    notes: `Distinct ${animal.scientific} reconstruction; ${animal.archetype} archetype, ${animal.feature} visible feature, ${animal.habitat} habitat. Human-only exhibit decisions remain pending.`,
    accessDate: catalog.accessDate,
  })),
}

await writeFile(join(root, sourcePath), `${JSON.stringify(intake, null, 2)}\n`)
console.log(sourcePath)
console.log(rankingPath)
