import {
  modelPreviewProfiles,
  type ModelPreviewFileName,
} from '../viewer/model-preview-profiles'

export type LocalReviewAnimalId =
  | 'stegosaurus'
  | 'pachycephalosaurus'
  | 'ichthyosaur'
  | 'pteranodon'
  | 'tyrannosaurus-rex'
  | 'triceratops'
  | 'apatosaurus'
  | 'gigantoraptor'
  | 'mammoth'
  | 'maiasaura'
  | 'plesiosaurus'
  | 'megalodon'
  | 'sauropelta'
  | 'dilophosaurus'
  | 'mosasaurus'
  | 'rhamphorhynchus'
  | 'tupandactylus'
  | 'meganeura'
  | 'velociraptor'
  | 'parasaurolophus'
  | 'dunkleosteus'
  | 'ammonite'
  | 'jaekelopterus'
  | 'smilodon'
  | 'spinosaurus'
  | 'allosaurus'
  | 'brachiosaurus'
  | 'quetzalcoatlus'
  | 'elasmosaurus'
  | 'woolly-rhinoceros'
  | 'anomalocaris'
  | 'albertosaurus'
  | 'carnotaurus'
  | 'ceratosaurus'
  | 'coelophysis'
  | 'compsognathus'
  | 'deinonychus'
  | 'baryonyx'
  | 'giganotosaurus'
  | 'suchomimus'
  | 'oviraptor'
  | 'therizinosaurus'
  | 'archaeopteryx'
  | 'sinosauropteryx'
  | 'monolophosaurus'
  | 'herrerasaurus'
  | 'utahraptor'
  | 'acrocanthosaurus'
  | 'carcharodontosaurus'
  | 'microraptor'
  | 'diplodocus'
  | 'argentinosaurus'
  | 'brontosaurus'
  | 'camarasaurus'
  | 'plateosaurus'
  | 'ankylosaurus'
  | 'euoplocephalus'
  | 'kentrosaurus'
  | 'protoceratops'
  | 'styracosaurus'
  | 'pachyrhinosaurus'
  | 'diabloceratops'
  | 'iguanodon'
  | 'edmontosaurus'
  | 'corythosaurus'
  | 'lambeosaurus'
  | 'gallimimus'
  | 'psittacosaurus'
  | 'heterodontosaurus'
  | 'dryosaurus'
  | 'nigersaurus'
  | 'dimorphodon'
  | 'anhanguera'
  | 'tapejara'
  | 'nyctosaurus'
  | 'dsungaripterus'
  | 'kronosaurus'
  | 'liopleurodon'
  | 'tylosaurus'
  | 'ophthalmosaurus'
  | 'shonisaurus'
  | 'nothosaurus'
  | 'placodus'
  | 'dimetrodon'
  | 'lystrosaurus'
  | 'gorgonops'
  | 'inostrancevia'
  | 'postosuchus'
  | 'desmatosuchus'
  | 'megaloceros'
  | 'glyptodon'
  | 'megatherium'
  | 'doedicurus'
  | 'paraceratherium'
  | 'gomphotherium'
  | 'macrauchenia'
  | 'thylacoleo'
  | 'opabinia'
  | 'hallucigenia'
  | 'titanoboa'

export function reviewAssetUrl(
  animalId: LocalReviewAnimalId,
  fileName:
    | 'model.glb'
    | 'background-landscape'
    | 'background-portrait'
    | 'narration.mp3'
    | 'poster.webp'
    | 'poster-portrait.webp'
    | 'thumbnail.webp'
    | 'model-preview.manifest.json'
    | ModelPreviewFileName,
): string {
  return `/__museum-review-assets/${animalId}/${fileName}`
}

export const reviewModelPreviewFileNames = modelPreviewProfiles.map(
  ({ fileName }) => fileName,
)
